#!/bin/bash

OUTPUT=/tmp/jqx.o

if test $# -ne 3; then
 echo "Script needs for 3 argument but actual $#" > $OUTPUT; exit 11
fi

OPTION="$1"
JSON_FILE="$2"
JSON_QUERY="$3"

for it in OPTION JSON_FILE JSON_QUERY; do
 if test -z "${!it}"; then echo "$it is empty!" > $OUTPUT; exit 11; fi; done

case "$OPTION" in
 -sfs) JSON_OPTION="select((.!=null)and(type==\"string\")and(.!=\"\"))";;
 -si) JSON_OPTION="select((.!=null)and(type==\"number\"))";;
 *) echo "Option \"$OPTION\" is not supported!" > $OUTPUT; exit 21;;
esac

CODE=0
RESULT="$(jq -Mcer "${JSON_QUERY}|${JSON_OPTION}" $JSON_FILE)"; CODE=$?
if test $CODE -ne 0; then
 echo "Json parse error $CODE!" > $OUTPUT; exit 31
fi

echo "$RESULT"

exit 0
