name: Verify

on:
  workflow_dispatch:
    inputs:
      git_source:
        description: "GIT source name. For example [dev, wip...]."
        required: true
        default: "dev"
      build_variant:
        description: "Android build variant name (build flavor + build type). For example [debug, release...]."
        required: true
        default: "debug"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      REPOSITORY_OWNER: kepocnhh
      REPOSITORY_NAME: AndroidActionsSample
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      TELEGRAM_BOT_ID: ${{secrets.TELEGRAM_BOT_ID}}
      TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
      TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
    steps:
      - run: |
          echo "HOME=$(echo ~)" >> $GITHUB_ENV
          echo "BUILD_PATH=$HOME/$(jq -r .workflow $GITHUB_EVENT_PATH | base64)/$GITHUB_RUN_NUMBER/$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GIT_SOURCE=${{github.event.inputs.git_source}}" >> $GITHUB_ENV
          if test "$VCS_PAT" == ""; then exit 1; fi
      - run: |
          mkdir -p $BUILD_PATH/repository
          git -C $BUILD_PATH/repository init
          git -C $BUILD_PATH/repository remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git -C $BUILD_PATH/repository fetch --depth=1 origin $GIT_SOURCE
          git -C $BUILD_PATH/repository checkout FETCH_HEAD
      - run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_SOURCE=$GIT_SOURCE \
           -t image.verify:$GITHUB_RUN_NUMBER \
           -f $BUILD_PATH/repository/buildSrc/src/main/resources/docker/verify.docker $BUILD_PATH/repository
          echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" > $BUILD_PATH/env
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $BUILD_PATH/env
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $BUILD_PATH/env
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $BUILD_PATH/env
          echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID" >> $BUILD_PATH/env
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> $BUILD_PATH/env
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
           -e VCS_DOMAIN="https://api.github.com" \
           --env-file $BUILD_PATH/env \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER \
           /bin/bash repository/buildSrc/src/main/resources/bash/workflow/verify/main.sh
