name: Verify

on:
  workflow_dispatch:
    inputs:
      git_branch_src:
        description: "GIT branch source name. For example [wip, dev...]."
        required: true
        default: "wip"
      build_variant:
        description: "Android build variant name (build flavor + build type). For example [debug, release...]."
        required: true
        default: "debug"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "REPOSITORY_OWNER=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(jq -r .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "GIT_BRANCH_SRC=${{github.event.inputs.git_branch_src}}" >> $GITHUB_ENV
          echo "BUILD_VARIANT=${{github.event.inputs.build_variant}}" >> $GITHUB_ENV
          if test -z "$VCS_PAT"; then exit 21; fi
          mkdir -p repository
      - working-directory: repository
        run: |
          git init
          git remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git fetch --depth=1 origin $GIT_BRANCH_SRC
          git checkout FETCH_HEAD
          cat .github/env >> $GITHUB_ENV
      - working-directory: repository
        run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VERSION_CI_EXTENSION=$VERSION_CI_EXTENSION \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_BRANCH_SRC=$GIT_BRANCH_SRC \
           -t image.$GITHUB_RUN_ID:$GITHUB_RUN_NUMBER \
           -f buildSrc/src/main/resources/docker/checkout.FETCH_HEAD.docker .
      - env:
          KEYSTORES: ${{secrets.KEYSTORES}}
          KEYSTORE_FINGERPRINTS: ${{secrets.KEYSTORE_FINGERPRINTS}}
          TELEGRAM: ${{secrets.TELEGRAM}}
        run: |
          echo "REPOSITORY_OWNER=$REPOSITORY_OWNER" > $BUILD_PATH/env
          echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $BUILD_PATH/env
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $BUILD_PATH/env
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $BUILD_PATH/env
          echo "BUILD_VARIANT=$BUILD_VARIANT" >> $BUILD_PATH/env
          echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID" >> $BUILD_PATH/env
          echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID" >> $BUILD_PATH/env
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
           -e VCS_DOMAIN="https://api.github.com" \
           -e KEYSTORE="$(echo "$KEYSTORES" | jq -r ".${BUILD_VARIANT}.base64")" \
           -e KEYSTORE_PASSWORD="$(echo "$KEYSTORES" | jq -r ".${BUILD_VARIANT}.password")" \
           -e KEYSTORE_FINGERPRINT="$(echo "$KEYSTORE_FINGERPRINTS" | jq -re ".${BUILD_VARIANT}.sha256")" \
           --env-file $BUILD_PATH/env \
           --name container.verify image.verify:$GITHUB_RUN_NUMBER \
           /bin/bash repository/buildSrc/src/main/resources/bash/workflow/verify/main.sh
