name: Verify

on:
  workflow_dispatch:
    inputs:
      git_branch_src:
        description: "GIT branch source name. For example [wip, dev...]."
        required: true
        default: "wip"
      build_variant:
        description: "Android build variant name (build flavor + build type): [unstableDebug, stagingDebug, snapshotDebug, productionRelease]."
        required: true
        default: "unstableDebug"
      key_alias:
        description: "Key alias. For example [debug, release...]."
        required: true
        default: "debug"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      VCS_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "REPOSITORY_OWNER=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(jq -r .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "CI_BUILD_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GIT_BRANCH_SRC=${{github.event.inputs.git_branch_src}}" >> $GITHUB_ENV
          echo "BUILD_VARIANT=${{github.event.inputs.build_variant}}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{github.event.inputs.key_alias}}" >> $GITHUB_ENV
          if test -z "$VCS_PAT"; then exit 21; fi
          mkdir -p repository
      - working-directory: repository
        run: |
          git init
          git remote add origin https://$VCS_PAT@github.com/$REPOSITORY_OWNER/$REPOSITORY_NAME.git
          git fetch --depth=1 origin $GIT_BRANCH_SRC
          git checkout FETCH_HEAD
          cat .github/env/common >> $GITHUB_ENV
      - working-directory: repository
        run: |
          docker build --no-cache \
           --build-arg REPOSITORY_OWNER=$REPOSITORY_OWNER \
           --build-arg REPOSITORY_NAME=$REPOSITORY_NAME \
           --build-arg VERSION_CI_EXTENSION=$VERSION_CI_EXTENSION \
           --build-arg VCS_PAT=$VCS_PAT \
           --build-arg GIT_BRANCH_SRC=$GIT_BRANCH_SRC \
           -t=image.verify:$CI_BUILD_ID \
           -f=buildSrc/src/main/resources/docker/checkout.FETCH_HEAD.docker .
      - env:
          KEYSTORES: ${{secrets.KEYSTORES}}
          FINGERPRINTS: ${{secrets.FINGERPRINTS}}
          TELEGRAM: ${{secrets.TELEGRAM}}
        run: |
          docker run --rm \
           -e VCS_PAT=$VCS_PAT \
           -e VCS_DOMAIN="https://api.github.com" \
           -e REPOSITORY_OWNER=$REPOSITORY_OWNER \
           -e REPOSITORY_NAME=$REPOSITORY_NAME \
           -e CI_BUILD_ID=$CI_BUILD_ID \
           -e BUILD_VARIANT=$BUILD_VARIANT \
           -e KEY_ALIAS=$KEY_ALIAS \
           -e KEYSTORE="$(echo "$KEYSTORES" | base64 -d | jq -Mer .${KEY_ALIAS}.base64)" \
           -e KEYSTORE_PASSWORD="$(echo "$KEYSTORES" | base64 -d | jq -Mer .${KEY_ALIAS}.password)" \
           -e KEY_X509_SHA512="$(echo "$FINGERPRINTS" | base64 -d | jq -Mer .key.${KEY_ALIAS}.x509.sha512)" \
           -e TELEGRAM_BOT_ID="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".bot.continuousibot.id")" \
           -e TELEGRAM_BOT_TOKEN="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".bot.continuousibot.token")" \
           -e TELEGRAM_CHAT_ID="$(echo "$TELEGRAM" | base64 -d | jq -Mcer ".chat.kepocnhh.id")" \
           --name container.verify image.verify:$CI_BUILD_ID \
           ci/workflow/verify.sh
